export const ZIP_CODE_REGEX = /^\d{5}(?:-\d{4})?$/;
export const STREET_NUMBER_REGEX = /^\d+[a-zA-Z0-9-]*$/;
export const NON_US_COUNTRY_REGEX =
  /\b(canada|mexico|uk|united kingdom|france|germany|spain)\b/i;

export const STREET_SUFFIX_ALIASES: Record<string, string> = {
  avenue: "Ave",
  ave: "Ave",
  boulevard: "Blvd",
  blvd: "Blvd",
  circle: "Cir",
  cir: "Cir",
  court: "Ct",
  ct: "Ct",
  drive: "Dr",
  dr: "Dr",
  lane: "Ln",
  ln: "Ln",
  parkway: "Pkwy",
  pkwy: "Pkwy",
  place: "Pl",
  pl: "Pl",
  road: "Rd",
  rd: "Rd",
  square: "Sq",
  sq: "Sq",
  street: "St",
  st: "St",
  terrace: "Ter",
  ter: "Ter",
  trail: "Trl",
  trl: "Trl",
  way: "Way",
};

export const DIRECTIONAL_ALIASES: Record<string, string> = {
  n: "N",
  s: "S",
  e: "E",
  w: "W",
  ne: "NE",
  nw: "NW",
  se: "SE",
  sw: "SW",
};

export const STATE_NAMES_TO_CODE: Record<string, string> = {
  ALABAMA: "AL",
  ALASKA: "AK",
  ARIZONA: "AZ",
  ARKANSAS: "AR",
  CALIFORNIA: "CA",
  COLORADO: "CO",
  CONNECTICUT: "CT",
  DELAWARE: "DE",
  FLORIDA: "FL",
  GEORGIA: "GA",
  HAWAII: "HI",
  IDAHO: "ID",
  ILLINOIS: "IL",
  INDIANA: "IN",
  IOWA: "IA",
  KANSAS: "KS",
  KENTUCKY: "KY",
  LOUISIANA: "LA",
  MAINE: "ME",
  MARYLAND: "MD",
  MASSACHUSETTS: "MA",
  MICHIGAN: "MI",
  MINNESOTA: "MN",
  MISSISSIPPI: "MS",
  MISSOURI: "MO",
  MONTANA: "MT",
  NEBRASKA: "NE",
  NEVADA: "NV",
  "NEW HAMPSHIRE": "NH",
  "NEW JERSEY": "NJ",
  "NEW MEXICO": "NM",
  "NEW YORK": "NY",
  "NORTH CAROLINA": "NC",
  "NORTH DAKOTA": "ND",
  OHIO: "OH",
  OKLAHOMA: "OK",
  OREGON: "OR",
  PENNSYLVANIA: "PA",
  "RHODE ISLAND": "RI",
  "SOUTH CAROLINA": "SC",
  "SOUTH DAKOTA": "SD",
  TENNESSEE: "TN",
  TEXAS: "TX",
  UTAH: "UT",
  VERMONT: "VT",
  VIRGINIA: "VA",
  WASHINGTON: "WA",
  "WEST VIRGINIA": "WV",
  WISCONSIN: "WI",
  WYOMING: "WY",
  "DISTRICT OF COLUMBIA": "DC",
};

export const STATE_CODES = new Set(Object.values(STATE_NAMES_TO_CODE));
export const STREET_SUFFIX_WORDS = new Set(Object.keys(STREET_SUFFIX_ALIASES));

export const LOCAL_PROVIDER_CORRECTIONS = {
  NORMALIZED_STATE_TO_USPS_CODE: "normalized state to USPS code",
  NORMALIZED_STREET_SUFFIX: "normalized street suffix",
} as const;
